name: rentndeal_admin_panel
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # Utility Packages
  http: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  fl_chart: ^0.70.0
  image_picker: ^1.1.0
  url_launcher: ^6.1.12
  iconsax_flutter: ^1.0.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  smooth_page_indicator: ^1.1.0

  # State Management
  cupertino_icons: ^1.0.6
  velocity_x: ^4.1.2
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase Packages
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0


  # Product Specific
  readmore: ^3.0.0
  data_table_2: ^2.5.15
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.0


  # Web Specific
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0





flutter:
  uses-material-design: true

  # ----------- LOCAL ASSETS --------#
  assets:
    - assets/images/
    - assets/logos/

