// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv70cxlkwoxP-cytnV4kRjWaQi86QA9d0',
    appId: '1:285013628013:web:a9d4a149d7fddac50edb64',
    messagingSenderId: '285013628013',
    projectId: 'rentndeal-05',
    authDomain: 'rentndeal-05.firebaseapp.com',
    storageBucket: 'rentndeal-05.appspot.com',
    measurementId: 'G-T48VS6VPFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGF-Wlxyz8CgmlVKTvOaI3cuB85PhVEc',
    appId: '1:285013628013:android:4fe6b8dc29f8f2050edb64',
    messagingSenderId: '285013628013',
    projectId: 'rentndeal-05',
    storageBucket: 'rentndeal-05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZF9dUzELIhWCQvFBI4gWRzFsHvf2NYA',
    appId: '1:285013628013:ios:604d63522536cbcd0edb64',
    messagingSenderId: '285013628013',
    projectId: 'rentndeal-05',
    storageBucket: 'rentndeal-05.appspot.com',
    androidClientId: '285013628013-2ac5075el3gu1kcetpo66tgc3a8huvem.apps.googleusercontent.com',
    iosClientId: '285013628013-9h7mkdpob1gibhhnc1ft7ar1j6fkp37j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentndealAdminPanel',
  );
}
